const data = {
  login: {
    phoneNumber: "3809797979",
    password: "qweqweqwe123",
  },
  access_token: "Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJzdGFkaXVtQ3J1c2hKV1QiLCJzdWIiOiIwODNiZjNjOC1iOTM2LTQ2OTEtYWY4Yi00ZTJiODM5YTFjNTciLCJhdXRob3JpdGllcyI6WyJST0xFX1BMQVlFUiJdLCJpYXQiOjE2OTA0NTM4NTAsImV4cCI6MTY5MzA4MTg1MH0.sioERRqIBpGD5LXaXrf8Eq4JS95U-5U1zEaAfDhl7g44GaizWLl6qVpFQWhlc_u7FY-z2NSl42uLpQsso8VhVA",  
  "teams": {
    "7": {
        "wins": 42,
        "bg_color": "#3c3c3c",
        "filename": "9b60da43-69b5-4643-a15a-a6a30da37e24",
        "city": "Valhalla, Kansas",
        "short_name": "Mjolnirs",
        "team_id": 7,
        "city_short": "Valhalla",
        "losses": 12,
        "team_name": "Valhalla Mjolnirs"
    },
    "8": {
        "wins": 42,
        "bg_color": "#67b9ff",
        "filename": "e841d6da-d277-4b86-83e3-4fe2e89634e8",
        "city": "Atlantis, Alabama",
        "short_name": "Robosquids",
        "team_id": 8,
        "city_short": "Atlantis",
        "losses": 12,
        "team_name": "Atlantis Robosquids"
    },
    "153": {
        "wins": 42,
        "bg_color": "#602120",
        "filename": "a7bd9ee3-3978-47db-83e6-92ae20c7d9e5",
        "city": "Troy, AL",
        "short_name": "Troy",
        "team_id": 153,
        "city_short": null,
        "losses": 12,
        "team_name": "Troy, AL Post 70"
    },
    "154": {
        "wins": 42,
        "bg_color": "#00467f",
        "filename": "e2f918b9-b125-46b1-86d0-8e7d864b8276",
        "city": "Idaho Falls, ID",
        "short_name": "Idaho Falls",
        "team_id": 154,
        "city_short": null,
        "losses": 12,
        "team_name": "Idaho Falls, ID Post 56"
    }
  },
  "events": [
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 154,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 2,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-06-10T19:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 20578,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 153,
          "audio_broadcast_url": null,
          "group": 6
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 153,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 33,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-06-11T19:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 20579,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 154,
          "audio_broadcast_url": null,
          "group": 6
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 154,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 32,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-06-17T19:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 21161,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 153,
          "audio_broadcast_url": null,
          "group": 6
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 153,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 33,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-06-18T19:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 21162,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 154,
          "audio_broadcast_url": null,
          "group": 6
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 154,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 34,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-06-19T19:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 21163,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 153,
          "audio_broadcast_url": null,
          "group": 6
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 153,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 34,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-06-20T19:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 21164,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 154,
          "audio_broadcast_url": null,
          "group": 6
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 154,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 2,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-06-21T19:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 21169,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 153,
          "audio_broadcast_url": null,
          "group": 6
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 154,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 34,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-06-23T19:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 21177,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 153,
          "audio_broadcast_url": null,
          "group": 6
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 153,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 33,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-06-24T19:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 21178,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 154,
          "audio_broadcast_url": null,
          "group": 6
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 154,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 43,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-06-25T19:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 21181,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 153,
          "audio_broadcast_url": null,
          "group": 6
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 153,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 33,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-06-26T19:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 21182,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 154,
          "audio_broadcast_url": null,
          "group": 6
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 154,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 43,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-06-27T19:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 21184,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 153,
          "audio_broadcast_url": null,
          "group": 6
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 153,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 2,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-06-28T19:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 21185,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 154,
          "audio_broadcast_url": null,
          "group": 6
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 154,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 33,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-06-29T19:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 21188,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 153,
          "audio_broadcast_url": null,
          "group": 6
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 153,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 33,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-06-30T19:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 21189,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 154,
          "audio_broadcast_url": null,
          "group": 6
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 154,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 34,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-07-01T00:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 21192,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 153,
          "audio_broadcast_url": null,
          "group": 0
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 153,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 34,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-07-02T00:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 21193,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 154,
          "audio_broadcast_url": null,
          "group": 0
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 154,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 34,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-07-02T19:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 21194,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 153,
          "audio_broadcast_url": null,
          "group": 6
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 153,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 2,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-07-03T19:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 21195,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 154,
          "audio_broadcast_url": null,
          "group": 6
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 154,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 32,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-07-04T19:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 21196,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 153,
          "audio_broadcast_url": null,
          "group": 6
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 153,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 35,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-07-05T19:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 21197,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 154,
          "audio_broadcast_url": null,
          "group": 6
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 154,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 43,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-07-06T19:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 21198,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 153,
          "audio_broadcast_url": null,
          "group": 6
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 153,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 35,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-07-07T19:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 21199,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 154,
          "audio_broadcast_url": null,
          "group": 6
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 154,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 33,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-07-08T19:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 21206,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 153,
          "audio_broadcast_url": null,
          "group": 6
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 153,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 45,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-07-09T19:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 21207,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 154,
          "audio_broadcast_url": null,
          "group": 6
      },
      {
          "venue_name": "Keeter Stadium",
          "home_team_id": 154,
          "anthem": null,
          "venue_city": "Shelby,NC",
          "venue_url": null,
          "charity_image_id": 46,
          "capacity": null,
          "game_status": 0,
          "map_coordinates": null,
          "start_time": "2023-07-10T00:00:00.000+00:00",
          "venue_country": "USA",
          "event_id": 21208,
          "charity_id": null,
          "first_pitch": null,
          "away_team_id": 153,
          "audio_broadcast_url": null,
          "group": 0
      },
      {
          "game_status": 0,
          "venue_name": "Asgard Field",
          "start_time": "2023-07-28T06:49:45.258+00:00",
          "venue_country": "Asgard",
          "home_team_id": 7,
          "event_id": 21261,
          "anthem": "Billy Joel",
          "first_pitch": "Nolan Ryan",
          "away_team_id": 8,
          "venue_city": "Asgard",
          "audio_broadcast_url": "https://edge.mixlr.com/channel/okuqc",
          "group": 1
      },
      {
          "game_status": 0,
          "venue_name": "Keeter Stadium",
          "start_time": "2023-07-28T06:49:45.270+00:00",
          "venue_country": "Shelby",
          "home_team_id": 154,
          "event_id": 21262,
          "anthem": "Billy Joel",
          "first_pitch": "Nolan Ryan",
          "away_team_id": 153,
          "venue_city": "Shelby",
          "audio_broadcast_url": "https://edge.mixlr.com/channel/okuqc",
          "group": 1
      }
  ]
}

export default data